<TextStyle Leading='20' Name='DefaultFont'>
<FontCharacter Advance='5' Code='32' SourceFile='ui_defaultfont_0' SourceRect='0,0,8,22'/>
<FontCharacter Advance='5' Code='33' SourceFile='ui_defaultfont_0' SourceRect='8,0,16,22'/>
<FontCharacter Advance='6' Code='34' SourceFile='ui_defaultfont_0' SourceRect='16,0,25,22'/>
<FontCharacter Advance='9' Code='35' SourceFile='ui_defaultfont_0' SourceRect='25,0,37,22'/>
<FontCharacter Advance='9' Code='36' SourceFile='ui_defaultfont_0' SourceRect='37,0,49,22'/>
<FontCharacter Advance='15' Code='37' SourceFile='ui_defaultfont_0' SourceRect='49,0,67,22'/>
<FontCharacter Advance='11' Code='38' SourceFile='ui_defaultfont_0' SourceRect='67,0,81,22'/>
<FontCharacter Advance='3' Code='39' SourceFile='ui_defaultfont_0' SourceRect='81,0,87,22'/>
<FontCharacter Advance='6' Code='40' SourceFile='ui_defaultfont_0' SourceRect='87,0,96,22'/>
<FontCharacter Advance='6' Code='41' SourceFile='ui_defaultfont_0' SourceRect='96,0,105,22'/>
<FontCharacter Advance='7' Code='42' SourceFile='ui_defaultfont_0' SourceRect='105,0,115,22'/>
<FontCharacter Advance='10' Code='43' SourceFile='ui_defaultfont_0' SourceRect='115,0,128,22'/>
<FontCharacter Advance='5' Code='44' SourceFile='ui_defaultfont_0' SourceRect='128,0,136,22'/>
<FontCharacter Advance='6' Code='45' SourceFile='ui_defaultfont_0' SourceRect='136,0,145,22'/>
<FontCharacter Advance='5' Code='46' SourceFile='ui_defaultfont_0' SourceRect='145,0,153,22'/>
<FontCharacter Advance='5' Code='47' SourceFile='ui_defaultfont_0' SourceRect='153,0,161,22'/>
<FontCharacter Advance='9' Code='48' SourceFile='ui_defaultfont_0' SourceRect='161,0,173,22'/>
<FontCharacter Advance='9' Code='49' SourceFile='ui_defaultfont_0' SourceRect='173,0,185,22'/>
<FontCharacter Advance='9' Code='50' SourceFile='ui_defaultfont_0' SourceRect='185,0,197,22'/>
<FontCharacter Advance='9' Code='51' SourceFile='ui_defaultfont_0' SourceRect='197,0,209,22'/>
<FontCharacter Advance='9' Code='52' SourceFile='ui_defaultfont_0' SourceRect='209,0,221,22'/>
<FontCharacter Advance='9' Code='53' SourceFile='ui_defaultfont_0' SourceRect='221,0,233,22'/>
<FontCharacter Advance='9' Code='54' SourceFile='ui_defaultfont_0' SourceRect='233,0,245,22'/>
<FontCharacter Advance='9' Code='55' SourceFile='ui_defaultfont_0' SourceRect='0,22,12,44'/>
<FontCharacter Advance='9' Code='56' SourceFile='ui_defaultfont_0' SourceRect='12,22,24,44'/>
<FontCharacter Advance='9' Code='57' SourceFile='ui_defaultfont_0' SourceRect='24,22,36,44'/>
<FontCharacter Advance='5' Code='58' SourceFile='ui_defaultfont_0' SourceRect='36,22,44,44'/>
<FontCharacter Advance='5' Code='59' SourceFile='ui_defaultfont_0' SourceRect='44,22,52,44'/>
<FontCharacter Advance='10' Code='60' SourceFile='ui_defaultfont_0' SourceRect='52,22,65,44'/>
<FontCharacter Advance='10' Code='61' SourceFile='ui_defaultfont_0' SourceRect='65,22,78,44'/>
<FontCharacter Advance='10' Code='62' SourceFile='ui_defaultfont_0' SourceRect='78,22,91,44'/>
<FontCharacter Advance='9' Code='63' SourceFile='ui_defaultfont_0' SourceRect='91,22,103,44'/>
<FontCharacter Advance='17' Code='64' SourceFile='ui_defaultfont_0' SourceRect='103,22,123,44'/>
<FontCharacter Advance='11' Code='65' SourceFile='ui_defaultfont_0' SourceRect='123,22,137,44'/>
<FontCharacter Advance='11' Code='66' SourceFile='ui_defaultfont_0' SourceRect='137,22,151,44'/>
<FontCharacter Advance='12' Code='67' SourceFile='ui_defaultfont_0' SourceRect='151,22,166,44'/>
<FontCharacter Advance='12' Code='68' SourceFile='ui_defaultfont_0' SourceRect='166,22,181,44'/>
<FontCharacter Advance='11' Code='69' SourceFile='ui_defaultfont_0' SourceRect='181,22,195,44'/>
<FontCharacter Advance='10' Code='70' SourceFile='ui_defaultfont_0' SourceRect='195,22,208,44'/>
<FontCharacter Advance='12' Code='71' SourceFile='ui_defaultfont_0' SourceRect='208,22,223,44'/>
<FontCharacter Advance='11' Code='72' SourceFile='ui_defaultfont_0' SourceRect='223,22,237,44'/>
<FontCharacter Advance='5' Code='73' SourceFile='ui_defaultfont_0' SourceRect='237,22,245,44'/>
<FontCharacter Advance='9' Code='74' SourceFile='ui_defaultfont_0' SourceRect='0,44,12,66'/>
<FontCharacter Advance='11' Code='75' SourceFile='ui_defaultfont_0' SourceRect='12,44,26,66'/>
<FontCharacter Advance='9' Code='76' SourceFile='ui_defaultfont_0' SourceRect='26,44,38,66'/>
<FontCharacter Advance='13' Code='77' SourceFile='ui_defaultfont_0' SourceRect='38,44,54,66'/>
<FontCharacter Advance='11' Code='78' SourceFile='ui_defaultfont_0' SourceRect='54,44,68,66'/>
<FontCharacter Advance='12' Code='79' SourceFile='ui_defaultfont_0' SourceRect='68,44,83,66'/>
<FontCharacter Advance='11' Code='80' SourceFile='ui_defaultfont_0' SourceRect='83,44,97,66'/>
<FontCharacter Advance='12' Code='81' SourceFile='ui_defaultfont_0' SourceRect='97,44,112,66'/>
<FontCharacter Advance='11' Code='82' SourceFile='ui_defaultfont_0' SourceRect='112,44,126,66'/>
<FontCharacter Advance='11' Code='83' SourceFile='ui_defaultfont_0' SourceRect='126,44,140,66'/>
<FontCharacter Advance='9' Code='84' SourceFile='ui_defaultfont_0' SourceRect='140,44,152,66'/>
<FontCharacter Advance='11' Code='85' SourceFile='ui_defaultfont_0' SourceRect='152,44,166,66'/>
<FontCharacter Advance='11' Code='86' SourceFile='ui_defaultfont_0' SourceRect='166,44,180,66'/>
<FontCharacter Advance='17' Code='87' SourceFile='ui_defaultfont_0' SourceRect='180,44,200,66'/>
<FontCharacter Advance='11' Code='88' SourceFile='ui_defaultfont_0' SourceRect='200,44,214,66'/>
<FontCharacter Advance='11' Code='89' SourceFile='ui_defaultfont_0' SourceRect='214,44,228,66'/>
<FontCharacter Advance='9' Code='90' SourceFile='ui_defaultfont_0' SourceRect='228,44,240,66'/>
<FontCharacter Advance='5' Code='91' SourceFile='ui_defaultfont_0' SourceRect='240,44,248,66'/>
<FontCharacter Advance='5' Code='92' SourceFile='ui_defaultfont_0' SourceRect='248,44,256,66'/>
<FontCharacter Advance='5' Code='93' SourceFile='ui_defaultfont_0' SourceRect='0,66,8,88'/>
<FontCharacter Advance='7' Code='94' SourceFile='ui_defaultfont_0' SourceRect='8,66,18,88'/>
<FontCharacter Advance='9' Code='95' SourceFile='ui_defaultfont_0' SourceRect='18,66,30,88'/>
<FontCharacter Advance='6' Code='96' SourceFile='ui_defaultfont_0' SourceRect='30,66,39,88'/>
<FontCharacter Advance='9' Code='97' SourceFile='ui_defaultfont_0' SourceRect='39,66,51,88'/>
<FontCharacter Advance='9' Code='98' SourceFile='ui_defaultfont_0' SourceRect='51,66,63,88'/>
<FontCharacter Advance='9' Code='99' SourceFile='ui_defaultfont_0' SourceRect='63,66,75,88'/>
<FontCharacter Advance='9' Code='100' SourceFile='ui_defaultfont_0' SourceRect='75,66,87,88'/>
<FontCharacter Advance='9' Code='101' SourceFile='ui_defaultfont_0' SourceRect='87,66,99,88'/>
<FontCharacter Advance='5' Code='102' SourceFile='ui_defaultfont_0' SourceRect='99,66,107,88'/>
<FontCharacter Advance='9' Code='103' SourceFile='ui_defaultfont_0' SourceRect='107,66,119,88'/>
<FontCharacter Advance='9' Code='104' SourceFile='ui_defaultfont_0' SourceRect='119,66,131,88'/>
<FontCharacter Advance='4' Code='105' SourceFile='ui_defaultfont_0' SourceRect='131,66,138,88'/>
<FontCharacter Advance='3' Code='106' SourceFile='ui_defaultfont_0' SourceRect='138,66,145,88'/>
<FontCharacter Advance='8' Code='107' SourceFile='ui_defaultfont_0' SourceRect='145,66,156,88'/>
<FontCharacter Advance='3' Code='108' SourceFile='ui_defaultfont_0' SourceRect='156,66,162,88'/>
<FontCharacter Advance='13' Code='109' SourceFile='ui_defaultfont_0' SourceRect='162,66,178,88'/>
<FontCharacter Advance='9' Code='110' SourceFile='ui_defaultfont_0' SourceRect='178,66,190,88'/>
<FontCharacter Advance='9' Code='111' SourceFile='ui_defaultfont_0' SourceRect='190,66,202,88'/>
<FontCharacter Advance='9' Code='112' SourceFile='ui_defaultfont_0' SourceRect='202,66,214,88'/>
<FontCharacter Advance='9' Code='113' SourceFile='ui_defaultfont_0' SourceRect='214,66,226,88'/>
<FontCharacter Advance='6' Code='114' SourceFile='ui_defaultfont_0' SourceRect='226,66,235,88'/>
<FontCharacter Advance='8' Code='115' SourceFile='ui_defaultfont_0' SourceRect='235,66,246,88'/>
<FontCharacter Advance='4' Code='116' SourceFile='ui_defaultfont_0' SourceRect='246,66,253,88'/>
<FontCharacter Advance='9' Code='117' SourceFile='ui_defaultfont_0' SourceRect='0,88,12,110'/>
<FontCharacter Advance='7' Code='118' SourceFile='ui_defaultfont_0' SourceRect='12,88,22,110'/>
<FontCharacter Advance='11' Code='119' SourceFile='ui_defaultfont_0' SourceRect='22,88,36,110'/>
<FontCharacter Advance='7' Code='120' SourceFile='ui_defaultfont_0' SourceRect='36,88,46,110'/>
<FontCharacter Advance='9' Code='121' SourceFile='ui_defaultfont_0' SourceRect='46,88,58,110'/>
<FontCharacter Advance='8' Code='122' SourceFile='ui_defaultfont_0' SourceRect='58,88,69,110'/>
<FontCharacter Advance='6' Code='123' SourceFile='ui_defaultfont_0' SourceRect='69,88,78,110'/>
<FontCharacter Advance='5' Code='124' SourceFile='ui_defaultfont_0' SourceRect='78,88,86,110'/>
<FontCharacter Advance='6' Code='125' SourceFile='ui_defaultfont_0' SourceRect='86,88,95,110'/>
<FontCharacter Advance='10' Code='126' SourceFile='ui_defaultfont_0' SourceRect='95,88,108,110'/>
</TextStyle>
