	<Namespace Name='E3Styles' size='128,64'>
		<Namespace Name='FlowImages' size='128,64'>
			<ImageStyle Name='flowInnerCornerLL'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='136,64,167,88'/>
			</ImageStyle>
			<ImageStyle Name='flowLMFat'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='118,176,119,247'/>
			</ImageStyle>
			<ImageStyle Name='flowInnerLM'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='160,168,161,175'/>
			</ImageStyle>
			<ImageStyle Name='flowInnerCornerUL'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='136,8,167,47'/>
			</ImageStyle>
			<ImageStyle Name='flowBack'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='40,8,136,80'/>
			</ImageStyle>
			<ImageStyle Name='flowML'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='104,82,136,83'/>
			</ImageStyle>
			<ImageStyle Name='flowCornerLL'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='104,88,136,136'/>
			</ImageStyle>
			<ImageStyle Name='flowContR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='64,24,172,104'/>
			</ImageStyle>
			<ImageStyle Name='flowButtonRight'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='232,176,256,248'/>
			</ImageStyle>
			<ImageStyle Name='flowButtonLeft'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='200,176,224,248'/>
			</ImageStyle>
			<ImageStyle Name='flowButtonMiddle'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='224,176,232,248'/>
			</ImageStyle>
			<ImageStyle Name='flowInnerML'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='136,43,152,44'/>
			</ImageStyle>
			<ImageStyle Name='logo'>
				<ImageFrame Source='ui_w_logo' SourceRect='72,0,255,167'/>
			</ImageStyle>
			<ImageStyle Name='flowInnerUM'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='165,8,166,24'/>
			</ImageStyle>
			<ImageStyle Name='logoCap'>
				<ImageFrame Source='ui_w_logo' SourceRect='72,176,255,224'/>
			</ImageStyle>
			<ImageStyle Name='logoRM'>
				<ImageFrame Source='ui_w_logo' SourceRect='72,168,255,176'/>
			</ImageStyle>
			<ImageStyle Name='flowLMSkinny'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='225,8,229,80'/>
			</ImageStyle>
			<ImageStyle Name='back'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='44,211,45,212'/>
			</ImageStyle>
			<ImageStyle Name='flowLMSkinny'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='194,176,195,247'/>
			</ImageStyle>
			<ImageStyle Name='flowPrev'>
				<ImageFrame Source='ui_w_buttons_02' SourceRect='40,176,119,247'/>
			</ImageStyle>
			<ImageStyle Name='splash'>
				<ImageFrame Source='ui_swglogo256' SourceRect='0,0,255,255'/>
			</ImageStyle>
		</Namespace>
		<Namespace Name='WindowImages' size='128,64'>
			<ImageStyle Name='windowML'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='88,192,95,193'/>
			</ImageStyle>
			<ImageStyle Name='windowMR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='112,200,119,207'/>
			</ImageStyle>
			<ImageStyle Name='windowLR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='112,208,119,215'/>
			</ImageStyle>
			<ImageStyle Name='windowUR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='112,184,119,191'/>
			</ImageStyle>
			<ImageStyle Name='windowLL'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='88,208,95,215'/>
			</ImageStyle>
			<ImageStyle Name='windowLM'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='96,208,97,215'/>
			</ImageStyle>
			<ImageStyle Name='windowUM'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='96,184,99,191'/>
			</ImageStyle>
			<ImageStyle Name='windowUL'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='88,184,95,191'/>
			</ImageStyle>
			<ImageStyle Name='windowM'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='100,200,101,201'/>
			</ImageStyle>
		</Namespace>
		<Namespace Name='Prefabs' size='128,64'/>
		<Namespace Name='PanelImages' size='128,64'>
			<ImageStyle Name='panelCapR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='136,120,151,167'/>
			</ImageStyle>
			<ImageStyle Name='panelL'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='152,120,174,167'/>
			</ImageStyle>
			<ImageStyle Name='panelM'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='170,120,172,167'/>
			</ImageStyle>
		</Namespace>
		<Namespace Name='Buttons' size='128,64'>
			<Namespace Name='prev' size='128,64'>
				<ButtonStyle Name='style' NormalTextStyle='bold_18' ReleaseSound='ui_deselect' RStyleDefault='rs_default'/>
				<ImageStyle Name='normal' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='0,48,71,95'/>
				</ImageStyle>
				<ImageStyle Name='hover' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='0,96,71,143'/>
				</ImageStyle>
				<ImageStyle Name='click' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='0,144,71,191'/>
				</ImageStyle>
				<RectangleStyle Center='normal' Name='rs_default'/>
			</Namespace>
			<Namespace Name='next' size='128,64'>
				<ButtonStyle Name='style' NormalTextStyle='bold_18' ReleaseSound='ui_deselect'/>
				<ImageStyle Name='normal' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='184,48,255,95'/>
				</ImageStyle>
				<ImageStyle Name='hover' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='184,96,255,143'/>
				</ImageStyle>
				<ImageStyle Name='click' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='184,144,255,191'/>
				</ImageStyle>
			</Namespace>
			<Namespace Name='finish' size='128,64'>
				<ButtonStyle Name='style' NormalTextStyle='bold_18' ReleaseSound='ui_deselect' RStyleActivated='rs_activated' RStyleDefault='rs_default' RStyleMouseOver='rs_hover'/>
				<ImageStyle Name='normal' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='112,192,167,239'/>
				</ImageStyle>
				<ImageStyle Name='hover' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='56,192,111,239'/>
				</ImageStyle>
				<ImageStyle Name='click' size='128,64'>
					<ImageFrame Source='ui_w_buttons_01' SourceRect='0,192,55,239'/>
				</ImageStyle>
				<RectangleStyle Center='normal' Name='rs_default'/>
				<RectangleStyle Center='click' Name='rs_activated'/>
				<RectangleStyle Center='hover' Name='rs_hover'/>
			</Namespace>
			<Namespace Name='cancel' size='128,64'>
				<ButtonStyle Name='style' NormalTextStyle='bold_18' ReleaseSound='ui_deselect' RStyleActivated='rs_activated' RStyleDefault='rs_default' RStyleMouseOver='rs_hover'/>
				<ImageStyle Name='normal' size='128,64'>
					<ImageFrame Source='ui_w_buttons_02' SourceRect='0,48,37,95'/>
				</ImageStyle>
				<ImageStyle Name='hover' size='128,64'>
					<ImageFrame Source='ui_w_buttons_02' SourceRect='0,96,37,143'/>
				</ImageStyle>
				<ImageStyle Name='click' size='128,64'>
					<ImageFrame Source='ui_w_buttons_02' SourceRect='0,144,37,191'/>
				</ImageStyle>
				<RectangleStyle Center='normal' Name='rs_default'/>
				<RectangleStyle Center='click' Name='rs_activated'/>
				<RectangleStyle Center='hover' Name='rs_hover'/>
			</Namespace>
			<Namespace Name='genderMale' size='128,64'>
				<ButtonStyle Name='style' NormalTextStyle='bold_18' ReleaseSound='ui_deselect' RStyleActivated='rs_activated' RStyleDefault='rs_default' RStyleMouseOver='rs_hover'/>
				<ImageStyle Name='normal' size='128,64'>
					<ImageFrame Source='ui_w_buttons_03' SourceRect='216,72,249,104'/>
				</ImageStyle>
				<ImageStyle Name='click' size='128,64'>
					<ImageFrame Source='ui_w_buttons_03' SourceRect='216,72,249,104'/>
				</ImageStyle>
				<ImageStyle Name='hover' size='128,64'>
					<ImageFrame Source='ui_w_buttons_03' SourceRect='216,72,249,104'/>
				</ImageStyle>
				<RectangleStyle Center='normal' Name='rs_default'/>
				<RectangleStyle Center='click' Name='rs_activated'/>
				<RectangleStyle Center='hover' Name='rs_hover'/>
			</Namespace>
			<Namespace Name='genderFemale' size='128,64'>
				<ButtonStyle Name='style' NormalTextStyle='bold_18' ReleaseSound='ui_deselect' RStyleActivated='rs_activated' RStyleDefault='rs_default' RStyleMouseOver='rs_hover'/>
				<ImageStyle Name='normal' size='128,64'>
					<ImageFrame Source='ui_rebel_buttons' SourceRect='430,314,461,342'/>
				</ImageStyle>
				<ImageStyle Name='click' size='128,64'>
					<ImageFrame Source='ui_w_buttons_03' SourceRect='216,72,249,104'/>
				</ImageStyle>
				<ImageStyle Name='hover' size='128,64'>
					<ImageFrame Source='ui_w_buttons_03' SourceRect='176,72,208,104'/>
				</ImageStyle>
				<RectangleStyle Center='normal' Name='rs_default'/>
				<RectangleStyle Center='click' Name='rs_activated'/>
				<RectangleStyle Center='hover' Name='rs_hover'/>
			</Namespace>
		</Namespace>
		<Namespace Name='messageboxImages' size='128,64'>
			<ImageStyle Name='windowML'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='8,208,40,216'/>
			</ImageStyle>
			<ImageStyle Name='windowMR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='48,208,80,215'/>
			</ImageStyle>
			<ImageStyle Name='windowLR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='48,216,80,248'/>
			</ImageStyle>
			<ImageStyle Name='windowUR'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='48,176,80,208'/>
			</ImageStyle>
			<ImageStyle Name='windowLL'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='8,216,40,248'/>
			</ImageStyle>
			<ImageStyle Name='windowLM'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='40,216,48,248'/>
			</ImageStyle>
			<ImageStyle Name='windowUM'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='40,176,47,207'/>
			</ImageStyle>
			<ImageStyle Name='windowUL'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='8,176,40,208'/>
			</ImageStyle>
			<ImageStyle Name='windowM'>
				<ImageFrame Source='ui_w_buttons_03' SourceRect='39,212,40,213'/>
			</ImageStyle>
		</Namespace>
		<ImageStyle Name='animtest' size='64,64'>
			<ImageFrame Name='1' SourceRect='0,0,32,32'/>
			<ImageFrame Name='2' SourceRect='32,0,64,32'/>
			<ImageFrame Name='3' SourceRect='0,32,32,64'/>
			<ImageFrame Name='4' SourceRect='32,32,64,64'/>
		</ImageStyle>
		<Namespace Name='Checkbox' size='128,64'>
			<ImageStyle Name='checkedImage' size='128,64'>
				<ImageFrame Name='checked' Source='ps_interface_art_00' SourceRect='17,105,34,121'/>
			</ImageStyle>
			<CheckboxStyle Name='Style' NormalCheckedImage='checkedImage' NormalTextStyle='bold_18' NormalUncheckedImage='uncheckedImage' TextOffset='24,0'/>
			<ImageStyle Name='uncheckedImage' size='128,64'>
				<ImageFrame Name='unchecked' Source='ps_interface_art_00' SourceRect='0,105,17,121'/>
			</ImageStyle>
		</Namespace>
		<Namespace Name='Dropdown' size='128,64'>
			<Namespace Name='default' size='128,64'>
				<DropdownboxStyle DropBy='180' Listbox.Style='/DefaultListboxStyle' Name='style' Normal.Background='/top_Buttons.roundButton.normal_middle' Normal.DownArrow='/top_Buttons.roundButton.normal_right' Normal.StartCap='/top_Buttons.roundButton.normal_left' Padding='8,12,0,0' Pressed.DownArrow='/top_Buttons.roundButton.pressed_right' Scrollbar.Style='/Styles.scrollbar.default.v.style' Selected.DownArrow='/top_Buttons.roundButton.hover_right'/>
			</Namespace>
		</Namespace>
		<Namespace Name='Slider' size='128,64'>
			<Namespace Name='default' size='128,64'>
				<Namespace Name='horizontal' size='128,64'>
					<SliderbarStyle background='normal_middle' endcap='normal_end' Name='style' size='128,64' slider='/top_Buttons.roundButton.pressed_right' startcap='normal_start'/>
					<ImageStyle Name='normal_end' size='128,64'>
						<ImageFrame Source='ui_cust_common_new' SourceRect='92,204,168,253'/>
					</ImageStyle>
					<ImageStyle Name='normal_start' size='128,64'>
						<ImageFrame Source='ui_cust_common_new' SourceRect='1,204,75,253'/>
					</ImageStyle>
					<ImageStyle Name='normal_middle' size='128,64'>
						<ImageFrame Source='ui_cust_common_new' SourceRect='92,204,93,253'/>
					</ImageStyle>
				</Namespace>
				<Namespace Name='vertical' size='128,64'>
					<SliderbarStyle background='normal_middle' Layout='Vertical' Name='style' size='128,64' slider='/top_Buttons.roundButton.pressed_right'/>
					<ImageStyle Name='normal_middle' size='128,64'>
						<ImageFrame Source='ui_w_buttons_01' SourceRect='97,51,157,63'/>
					</ImageStyle>
				</Namespace>
			</Namespace>
		</Namespace>
		<Namespace Name='e3Window'>
			<RectangleStyle Center='WindowImages.windowM' East='WindowImages.windowMR' Name='style' North='WindowImages.windowUM' NorthEast='WindowImages.windowUR' NorthWest='WindowImages.windowUL' South='WindowImages.windowLM' SouthEast='WindowImages.windowLR' SouthWest='WindowImages.windowLL' West='WindowImages.windowML'/>
			<RectangleStyle Center='rect_style_basic_images.c' CenterStretchH='false' East='rect_style_basic_images.e' Name='rect_style_basic' North='rect_style_basic_images.n' NorthEast='rect_style_basic_images.ne' NorthWest='rect_style_basic_images.nw' South='rect_style_basic_images.s' SouthEast='rect_style_basic_images.se' SouthWest='rect_style_basic_images.sw' West='rect_style_basic_images.w'/>
			<Namespace Name='rect_style_basic_images'>
				<ImageStyle Name='ne'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='137,147,169,180'/>
				</ImageStyle>
				<ImageStyle Name='nw'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='170,147,202,180'/>
				</ImageStyle>
				<ImageStyle Name='n'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='169,147,170,180'/>
				</ImageStyle>
				<ImageStyle Name='w'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='137,179,169,180'/>
				</ImageStyle>
				<ImageStyle Name='e'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='170,179,202,180'/>
				</ImageStyle>
				<ImageStyle Name='se'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='170,179,202,212'/>
				</ImageStyle>
				<ImageStyle Name='sw'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='137,179,169,212'/>
				</ImageStyle>
				<ImageStyle Name='s'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='169,179,170,212'/>
				</ImageStyle>
				<ImageStyle Name='c'>
					<ImageFrame Source='ui_rebel_hud' SourceRect='168,177,169,178'/>
				</ImageStyle>
			</Namespace>
		</Namespace>
		<Namespace Name='ThickWindow'>
			<RectangleStyle Center='messageboxImages.windowM' East='messageboxImages.windowMR' Name='style' North='messageboxImages.windowUM' NorthEast='messageboxImages.windowUR' NorthWest='messageboxImages.windowUL' South='messageboxImages.windowLM' SouthEast='messageboxImages.windowLR' SouthWest='messageboxImages.windowLL' West='messageboxImages.windowML'/>
		</Namespace>
	</Namespace>
