	<Namespace
		Name='Fonts'
	>
		<include>font/aurabesh_12.inc</include>
		<include>font/aurabesh_18.inc</include>
		<include>font/aurabesh_24.inc</include>
		<include>font/lucida_console_12.inc</include>
		<include>font/lucida_console_14.inc</include>
		<include>font/verdana_12.inc</include>
		<include>font/verdana_13.inc</include>
		<include>font/verdana_14.inc</include>
		<include>font/verdana_16.inc</include>
		<include>font/verdana_17.inc</include>
		<include>font/verdana_18.inc</include>
		<include>font/verdana_20.inc</include>
		<include>font/verdana_22.inc</include>
		<include>font/verdana_bold_12.inc</include>
		<include>font/verdana_bold_13.inc</include>
		<include>font/verdana_bold_14.inc</include>
		<include>font/verdana_bold_16.inc</include>
		<include>font/verdana_bold_17.inc</include>
		<include>font/verdana_bold_18.inc</include>
		<include>font/verdana_bold_20.inc</include>
		<include>font/verdana_bold_22.inc</include>
		<include>font/verdana_bold_24.inc</include>
	</Namespace>
