<Namespace Name='VScrollbar'>
<ImageStyle Name='startcap.normal'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='356,262,374,286'/>
</ImageStyle>
<ImageStyle Name='startcap.disabled'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='333,261,351,285'/>
</ImageStyle>
<ImageStyle Name='startcap.pressed'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='309,260,327,284'/>
</ImageStyle>
<ImageStyle Name='endcap.normal'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='356,311,374,335'/>
</ImageStyle>
<ImageStyle Name='endcap.disabled'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='333,312,351,336'/>
</ImageStyle>
<ImageStyle Name='endcap.pressed'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='309,313,327,337'/>
</ImageStyle>
<ImageStyle Name='background.normal'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='356,299,374,300'/>
</ImageStyle>
<ImageStyle Name='thumb.startcap.normal'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='365,338,386,344'/>
</ImageStyle>
<ImageStyle Name='thumb.background.normal'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='365,344,386,345'/>
</ImageStyle>
<ImageStyle Name='thumb.endcap.normal'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='365,344,386,350'/>
</ImageStyle>
<ScrollbarStyle Background.Disabled='background.disabled' Background.Normal='background.normal' EndCap.Disabled='endcap.disabled' EndCap.Normal='endcap.normal' EndCap.Pressed='endcap.pressed' EndCap.StopOffset='24' Name='style' OnDisableEffector='/New Page.FadeOutEffector' OnEnableEffector='/New Page.FadeInEffector' StartCap.Disabled='startcap.disabled' StartCap.Normal='startcap.normal' StartCap.Pressed='startcap.pressed' Startcap.StopOffset='24' Thumb.Background.Disabled='thumb.background.disabled' Thumb.Background.Normal='thumb.background.normal' Thumb.EndCap.Disabled='thumb.endcap.disabled' Thumb.EndCap.Normal='thumb.endcap.normal' Thumb.MinSize='30' Thumb.StartCap.Disabled='thumb.startcap.disabled' Thumb.StartCap.Normal='thumb.startcap.normal'/>
<ImageStyle Name='background.disabled'>
<ImageFrame Source='ui_rebel_buttons' SourceRect='353,286,374,312'/>
</ImageStyle>
</Namespace>
